#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

source ./script/sh/read_env
script/bootstrap

echo "==> Setting up project…"
# reset database to a fresh state.
eval "$(read_env)" mix ecto.reset
eval "$(read_env)" mix setup
eval "$(read_env)" MIX_ENV=test mix do ecto.drop, ecto.create
eval "$(read_env)" MIX_ENV=test mix ecto.migrate

echo "==> The project is setup! 🚀 Is there demo data to load?"
